version: '2'
services:
  fhem:
    container_name: fhem
    image: raigen/fhem:rpi-alpine
    volumes:
      - fhem-data:/opt/fhem
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    ports:
      - "8083:8083"
volumes:
  fhem-data:
    external: true
